### ISSUE TITLE
Some typos in script Algebra II

### ISSUE THREAD

**Issue by BastiaanCnossen** [Nicholas42/AlgebraFranke#13]
Hi guys,

First: thanks a lot for writing these notes. It is especially helpful that you always fill in details that Franke didn't do properly and that you sometimes rewrite results/proofs to make them clearer!

When reading the script of algebra II, I caught some mistakes that could lead to confusion, and I decided to share them with you again. And because this will be a long message anyway, after it I will also include some typos that won't be confusing to anyone, but still look better when corrected.
Beware: this will be a looooong comment...

- p. 4, The part of the proof of corollary 1 after 'on the other hand' seems redundant. For proving that C_i = V(p_i) has codimension 1 it is enough to show that ht(p_i)<=1 and this already follows from p_i being minimal among the prime ideals containing f as proved in the first paragraph of the proof.

- p. 5, Step 2. First of all: 'Wma that k is minimal' can better be replaced by 'Wma that g is chosen such that k is minimal', since otherwise it sounds a priori as if the prime decomposition of g is chosen with a minimal number of prime factors, which doesn't make sense. Also once you wrote 'q' instead of 'q_1'.
But the suggestion that I actually would like to make for this paragraph is changing the argument altogether by noticing after writing 'g = q_1...q_k' that one of the q_i must be in q\{0} as q is prime, and continuing the argument with g = q_i. (This is nicer, since you have a direct contradiction as then q_i and p only differ by a unit by p|q_i, so p \in q)

- p. 15: Question: In Example 1, when defining the derivation d from a given tuple (m_1, ... , m_n) shouldn't we evaluate the derivative \partial / \partial X_i somewhere, fore example in (0,...,0)? We want to end up with an element in M, right? But maybe I'm misunderstanding something here...

- p. 18: In the remark, it is important to say that the unique homomorphism t is _B-linear_, i.e. there might be more non-B-linear morphisms with the property.

- p. 48, Proof fact 1: Note that you use p_{\delta} twice for different things. In the current way of writing, this is confusing for the reader, since from the formula you give it follows that (\delta + 1)! q_{\delta + 1} = p_{\delta} holds, so _with_ a factorial instead of without. To make this clearer, you can better (anticipating on what you will do in lemma 3) rewrite the p_0, p_1, ..., p_\delta that you introduced in your proof with tildes, and remark totally on the end of the proof that \tilde{p}_ {\delta} = p_{\delta} / \delta! (I mean a factorial here.)

- p. 53, Proof: If I'm correct, you mean that 's \in S(x) \setminus q' instead of 's \in R \setminus p'. Also a few lines above I think it should say 's \notin q' instead of 's \notin p'.

- p. 67, comment after definition 3: You prove that if I is fractional, then so is I^{-1}, but I don't see where you use that I is fractional. You only need that I contains some element of R, but this is always the case for non-empty I as any element of K can be multiplied with some element of R to obtain an element of R and I is an R-module so contains such products. So it seems that I^{-1} is a fractional ideal in general, right?

- p. 67, proposition 1: You wrote that I_p is an ideal _in_ R_p, but this doesn't seem right since I is just any R-submodule of K. Franke used the terminology 'I \cdot R_p is a principal ideal _of_ R_p', which I would interpret as: 'I \cdot R_p is a fractional ideal of R_p, which is principal, i.e. generated by one element'. In the end, this is also exactly what you prove: I_p is generated by an element a_i which is not necessarily in R_p. 

- p. 69, proof of theorem 22: be aware that Franke restated the theorem in the new lecture before proving it and by accident swapped the meaning of (a) and (b). So in fact, in the way you wrote it in the script, the implication (b) to (a) is trivial, not the other way around. Also, I think you want to prove (a) to (c) and (c) to (a) instead of the implications to (b), since you just want to work with ideals of p. (Well, (b) to (c) works fine as it is, as (b) to (a) is trivial, but for the other direction only (c) to (a) seems to follow directly.)

Okay and so now the pedantic remarks on some other details. Don't worry about skipping these corrections for now (if not forever) because they're not as important as the previous ones.
- p. 4, proof of corollary 1: you wrote p_i \in O(X) instead of p_i \subset O(X).
- p. 5, top of the page: one could consider reminding the reader that \tilde{X} is again affine.
- p. 10, proof of proposition 1: The word 'conversely' is out of place here, since it suggests that you prove an equivalence, but you don't.
- p. 10, bottom of the page: I think the R_m should be R_{m_x} (okay, we know what you mean of course)
- p. 14, bottom of the page: You mean 'equivalent conditions' instead of 'equivalence conditions'.
- p. 15, bottom of the page: Since you will later use a lot that Der_R(A,M) \cong Hom_A(\Omega_{A/R}, M) in this exact form, it might be considerable to make some explicit remark that this is all the universal property actually says.
- p. 16, definition 3: It might be considerable to change 'We define' to 'For x \in M, we define' to make the paragraph clearer.
- p. 16, Remark (a): There is one equality-sign too many.
- p. 17, top of the page: For consistency it would be recommendable changing the 'F' to 'F_A' there, like you do in the rest of the proof.
- p. 19, top of the page: You mean 'using (3) and the ...'
- p. 20, In 'to show (d)...': You mean 'then d(a) = 0'.
- p. 34. Okay, maybe you think this is already clear enough as it is, but personally I would add explicitly in definition 5 that C(Z) is a subset of k^{n+1} (or A^{n+1}(k)).
- p. 36, example 1: it defines an isomorphism when multiplying with X_i^l, not with X_0^l.
- p. 41, in the remark: there is a space missing between 'over' and 'k'.
- p. 44, proposition 1 (e): You repeated the word 'infinite'. Also it seems to be more consistent to use the word 'descending' again instead of 'decreasing'. 
- p. 46, top of the page: The inclusions here are not necessarily strict, and in fact you will show that they aren't. Also some of the inclusions are the wrong way around. 
- p. 46, Step 4: You want J \subseteq I instead of the other way around. 
- p. 46, Step 5: The intersection shouldn't use 'i' as the variable, because i is already fixed.
- p. 48, proof fact 2, and on several other occasions in the document: 'on the other side' should be 'on the other hand'.
- p. 49, proof of proposition 3: When introducing the filtration of N, you used again the natural numbers t_i, which you already used in the filtration of M. (Okay, true, really nobody cares about it... I'm not even sure why I saw this...) You could replace them by s_i for example.
- p. 49, proof of prop 3: the irreducible components of V(p) \cap V(x) have codimension _smaller or equal to_ n-d+1, not larger or equal to as you wrote.
- p. 53, proposition 1 (b): The f_{U \cap V} should be f_{U \cap Y}.
- p. 54, in the diagram with the bijections, the prime ideals p are _subsets_ of O_X(X), not elements.
- p. 54, end of proof of def. 2: O_X(l) should be O_X(d).
- p. 57, middle of the page: because of copying and pasting, by accident two of your sums run up to k instead of up to n, and in some other places an 'n' is replaced by a 'k' as well. For some reason, Franke chose the filtration of M to have length n instead of k, in contrast to what is done in the rest of the text. To bring back consistency, you could also consider changing back all n's to k's in this proof. 
- p. 58, proof of lemma 1: you actually mean exactly the opposite with the inclusions: the first part proves that the right-hand side is a subset of the left-hand side (you proved: p not in left, then p not in right.) 
- p. 63. Corollary 7: the word 'is' is missing in 'This is also not corollary 4'. (Yeppp, even the non-serious parts of the script don't get spared!)
- p. 64, second paragraph. The original sentence by Franke was: 'l_R(M) <= C, hence l_R(R/p_i)<= C'. You added a lot of (admittedly necessary) text in between, so it might be considerable to start the new paragraph by repeating that l_R(M) <= C, so that the 'hence' makes sense again.
- p. 64, last paragraph: you have added a proof for the equality of the two radicals, but I wonder if you couldn't just skip it altogether by just saying that Ann_R(M) \subseteq Ann_R(N) so supp(N) \subseteq supp(M). You don't seem to use the equality of the sets anywhere. 
- p. 67, remark 1(b): the 'max' should be a 'min'.
- p. 68, bottom \equation environment: you forgot to write the valuation v(r_i x^i) and wrote only a minimum over r_i x^i. 

Well, that was it. I hope you can appreciate the mentioning of the typos, even though it will be a lot of work for you changing them.
Also, let me know if I was wrong in some of my corrections.

I wish you happy holidays!
Best,
Bastiaan

**Comment by FlorianAdler** [comment]
First of all a massive thank you for you spending seemingly a lot of time collecting all these mistakes and typos. I hope I fixed the best part of them.
 I would also like to comment on some of your suggestions and explain what I have changed and why.

- > p. 15: Question: In Example 1, when defining the derivation d from a given tuple (m_1, ... , m_n) shouldn't we evaluate the derivative \partial / \partial X_i somewhere, fore example in (0,...,0)? We want to end up with an element in M, right? But maybe I'm misunderstanding something here... 

M is actually an R[X_1,...,X_n]-module, so we don't need to evaluate the partial derivatives. Multipliying by them is just module multiplication (I also remarked this in the lecture notes as this is indeed confusing).

- > p. 67, comment after definition 3: You prove that if I is fractional, then so is I^{-1}, but I don't see where you use that I is fractional. You only need that I contains some element of R, but this is always the case for non-empty I as any element of K can be multiplied with some element of R to obtain an element of R and I is an R-module so contains such products. So it seems that I^{-1} is a fractional ideal in general, right?

I was quite surprised too, but totally agree with you.

- > p. 57, middle of the page: because of copying and pasting, by accident two of your sums run up to k instead of up to n, and in some other places an 'n' is replaced by a 'k' as well. For some reason, Franke chose the filtration of M to have length n instead of k, in contrast to what is done in the rest of the text. To bring back consistency, you could also consider changing back all n's to k's in this proof.

I kept them to be n's (but consistently now) -- it really ~p*ssed me off~ annoyed me how Franke kept using k for his indices when some field k was involved (ok, it was probably \mathfrak k in his notes, but anyway). 

- > p. 64, last paragraph: you have added a proof for the equality of the two radicals, but I wonder if you couldn't just skip it altogether by just saying that Ann_R(M) \subseteq Ann_R(N) so supp(N) \subseteq supp(M). You don't seem to use the equality of the sets anywhere.

Indeed. But I'd still like to keep this lemma as it is quite nice to know.

Your suggestions throughout the semester really helped us improving the readability and usability of our scripts.
I hope your exams went well and have a nice holiday
Ferdinand
